environment:
  matrix:
    - python : 27
    - python : 27-x64
    - python : 35
    - python : 35-x64
    - python : 36
    - python : 36-x64
    - python : 37
    - python : 37-x64

install:

  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install pip
  - python -m pip install --upgrade pip

  # Install the build and runtime dependencies of the project.
  - pip install setuptools pandas six joblib py_stringmatching nose cython
  - pip install pyprind==2.9.8

  - python setup.py build_ext --inplace


build: false

test_script:
  # run unit tests
  #- nosetests -v
  - nosetests py_stringsimjoin/tests/test_error.py -vs

on_success:
  - echo Build succesful
